### ISSUE TITLE
Add a `.gitignore` file to your github repository

### ISSUE THREAD

**Issue by miclovich** [macinnis82/blogful#1]
Hi Ryan,

do you mind adding the `env` to your git ignore file. We usually don't push Python virtual environments to Git or Github.

See ref: https://help.github.com/articles/ignoring-files/

**Comment by macinnis82** [comment]
Hi Victor -

I added the .gitignore file using the sample for Python from
https://github.com/github/gitignore/blob/master/Python.gitignore.

How do i clean up my git repo?

Thanks,
Ryan
